# Generated by Django 5.2.1 on 2025-06-01 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpulseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='IR name', max_length=200)),
                ('cabinet_type', models.CharField(help_text='Cabinet type', max_length=100)),
                ('microphone', models.CharField(blank=True, help_text='Microphone used', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to IR file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impulse Response',
                'verbose_name_plural': 'Impulse Responses',
                'db_table': 'app_impulse_response',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Amplifier name/model', max_length=200)),
                ('brand', models.CharField(db_index=True, help_text='Amplifier brand/manufacturer', max_length=100)),
                ('model', models.CharField(db_index=True, help_text='Specific model name', max_length=100)),
                ('power_rating', models.PositiveIntegerField(blank=True, help_text='Power rating in watts', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('tube_type', models.CharField(blank=True, help_text='Type of tubes used (e.g., 12AX7, EL34)', max_length=50)),
                ('channels', models.PositiveIntegerField(blank=True, help_text='Number of channels', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, help_text='Amplifier description and characteristics')),
                ('release_year', models.PositiveIntegerField(blank=True, help_text='Year the amplifier was released', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amplifier',
                'verbose_name_plural': 'Amplifiers',
                'db_table': 'app_amp',
                'ordering': ['brand', 'model'],
                'indexes': [models.Index(fields=['brand', 'model'], name='app_amp_brand_c71d5e_idx'), models.Index(fields=['power_rating'], name='app_amp_power_r_7cdaa6_idx'), models.Index(fields=['created_at'], name='app_amp_created_02adf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NAMRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(help_text='Band name', max_length=200)),
                ('description', models.TextField(help_text='Recommendation description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_amp', models.ForeignKey(blank=True, help_text='Recommended amplifier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.amp')),
                ('recommended_ir', models.ForeignKey(blank=True, help_text='Recommended impulse response', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.impulseresponse')),
            ],
            options={
                'verbose_name': 'NAM Recommendation',
                'verbose_name_plural': 'NAM Recommendations',
                'db_table': 'app_nam_recommendation',
                'ordering': ['-created_at'],
                'unique_together': {('band_name',)},
            },
        ),
    ]
