# Generated by Django 5.2.1 on 2025-06-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impulseresponse',
            name='file_path',
        ),
    ]
